### ISSUE TITLE
Latest version breaks syntax highlighting

### ISSUE THREAD

**Issue by amykyta3** [evandrocoan/Sublime3-Theme-NotepadPlusPlus#1] opened 2017-10-24 05:59 UTC
Syntax highlighting seems to have regressed in the latest update

I have narrowed it down to these two commits:
https://github.com/evandrocoan/SublimeNotepadPlusPlusTheme/commit/359a86499447bdedc3aef752c12ee8e60b5b1ef8
https://github.com/evandrocoan/SublimeNotepadPlusPlusTheme/commit/42abe7d47d888f063838822a793e671b7ad3f243

See images: https://imgur.com/a/tchfK

I am using Sublime v 3.0 on Linux
Above files are Python

**Comment by evandrocoan** [comment] 2017-10-24 14:01
Sorry for it. The problem is that on Sublime Text development build ~3147 the syntax has broken. But the fix for it also broke the syntax for the v3.0 or build 3143. I should not have pushed a new version yesterday. I just deleted it.

**Comment by amykyta3** [comment] 2017-10-25 05:27
Confirmed revert.
Thanks for the quick update!

**Comment by evandrocoan** [comment] 2018-01-14 01:25
This was fixed by merging: https://github.com/wbond/package_control_channel/pull/6814

**Closed as completed by evandrocoan** 2018-01-14 01:25 UTC
